# Generated by Django 3.1.1 on 2020-09-06 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppPOS', '0002_salesperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppPOS.salesperson'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPOS.category'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPOS.stock'),
        ),
    ]
