# Generated by Django 3.1.1 on 2020-09-07 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppPOS', '0004_auto_20200906_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppPOS.salesperson'),
        ),
    ]
