# Generated by Django 3.1.1 on 2020-09-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPOS', '0008_auto_20200907_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='create_dated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
