# Generated by Django 3.1.1 on 2020-09-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPOS', '0009_auto_20200907_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=9),
            preserve_default=False,
        ),
    ]
