# Generated by Django 3.1.1 on 2020-09-13 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppPOS', '0010_salesperson_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason_for_refund', models.TextField(max_length=400)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPOS.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPOS.stock')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='AppPOS.salesperson')),
            ],
        ),
    ]
